#!/bin/bash

set -e

OCB="ocamlbuild -use-ocamlfind"

TARGET=main
TEST_TARGET=test

COVERAGE_FLAGS=()
COVERAGE_FILE='bisect0001.out'
COVERAGE_REPORT='coverage.html'
COVERAGE_TAG_LINE='<**/*.*> and not <**/{lexer,parser}.*>: bisect'
BROWSER=chromium

rule() {
  case $1 in
    clean)    $OCB -clean;;
    native)   $OCB $TARGET.native;;
    byte)     $OCB $TARGET.byte;;
    all)      $OCB $TARGET.native $TARGET.byte;;
    test)     $OCB $TEST_TARGET.byte --;;
    coverage) $OCB -clean
              $OCB -tag-line "$COVERAGE_TAG_LINE" $TEST_TARGET.byte --
              bisect-report $COVERAGE_FILE -html $COVERAGE_REPORT -I ./_build/
              rm $COVERAGE_FILE
              $OCB -clean
              $BROWSER $COVERAGE_REPORT/index.html
              ;;
    *)        echo "Unknown action $1";;
  esac;
}

if [ $# -eq 0 ]; then
  rule all
else
  while [ $# -gt 0 ]; do
    rule $1;
    shift
  done
fi
