#!/bin/sh

set -e

eval `opam config env`

OCAMLBUILD='ocamlbuild'
FLAGS='-use-ocamlfind'

TARGET=main
TEST_TARGET=test

COVERAGE_FILE='bisect0001.out'
COVERAGE_REPORT='coverage.html'
COVERAGE_TAG_LINE='<**/*.*> and not <**/{lexer,parser}.*>: package(bisect), syntax(camlp4o)'

ocb() {
  $OCAMLBUILD $FLAGS $*
}

ocb_coverage() {
  $OCAMLBUILD $FLAGS -tag-line "$COVERAGE_TAG_LINE" $*
}

browse() {
  xdg-open $*
}

rule() {
  case $1 in
    clean)    ocb -clean;;
    native)   ocb $TARGET.native;;
    byte)     ocb $TARGET.byte;;
    all)      ocb $TARGET.native $TARGET.byte;;
    test)     ocb $TEST_TARGET.byte --;;
    coverage) ocb -clean
              ocb_coverage $TEST_TARGET.byte --
              bisect-report $COVERAGE_FILE -html $COVERAGE_REPORT -I ./_build/
              rm $COVERAGE_FILE
              ocb -clean
              browse $COVERAGE_REPORT/index.html
              ;;
    *)        echo "Unknown action $1";;
  esac;
}

if [ $# -eq 0 ]; then
  rule all
else
  while [ $# -gt 0 ]; do
    rule $1;
    shift
  done
fi
